---
apiVersion: v1
kind: Service
metadata:
  name: mock-sync-service
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: mock-sync-service
