---
resources:
  - ../base
configMapGenerator:
  - name: env-config
    behavior: merge
    literals:
      - ENV_ID='local'
      - ENV_PREFIX='my-'
      - EXTERNAL_DOMAIN_NAME='aws11.balionis.com'
