---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: mock-ingress
spec:
  rules:
    - http:
        paths:
          - path: /
            backend:
              serviceName: mock-sync-service
              servicePort: 8080
