---
configurations:
  - config.yaml
configMapGenerator:
  - name: env-config
    literals:
      - ENV_PREFIX=''

generatorOptions:
  disableNameSuffixHash: false

vars:
  - name: ENV_ID
    fieldref:
      fieldpath: data.ENV_ID
    objref:
      kind: ConfigMap
      name: env-config
      apiVersion: v1
  - name: EXTERNAL_DOMAIN_NAME
    fieldref:
      fieldpath: data.EXTERNAL_DOMAIN_NAME
    objref:
      kind: ConfigMap
      name: env-config
      apiVersion: v1
